In [1]:
import pandas as pd

In [81]:
class DataInfo:
    def __init__(self,df):
        self.df = df

    def info(self): 
        
        # Numero de filas
        print(f'\nFilas totales : {self.df.shape[0]} \n')
      
        # Numero de columnas
        print(f'\nColumnas totales : {self.df.shape[1]} \n')
        
        # Nombres de las columnas
        column_name =  self.df.columns 
        print(f'\nNombres de las columnas\n'+  f'\n{column_name} \n \n')
        
        # Tipo de datos (info)
        print(f'Info de los datos\n')
        data_summary = self.df.info() 
        
        # Valores nulos 
        null_values = self.df.isnull().sum() 
        print(f'\nValores nulos\n' +  f'\n{null_values} \n \n')

        # Estadística descriptiva
        describe =  self.df.describe() 
        print(f'\nEstadística descriptiva\n' + f'\n{describe} \n \n')
    
    def clean(self):
        # Cambiamos el nombre de la columna
        self.df.rename(columns={'Entity': 'Country'}, inplace=True)
        # Eliminamos una columna
        self.df.drop(columns='Code', inplace=True)
        print(self.df.columns)
    
    def dfcont(self):
        x = self.df[self.df['Country'].str.contains('WHO')].copy()
        x.rename(columns={'Country': 'Continent'}, inplace=True)
        return x
    def dfincome(self):
        x = self.df[self.df['Country'].str.contains('Bank')].copy()
        x.rename(columns={'Country': 'Income'}, inplace=True)
        return x

In [82]:
a = pd.read_csv('data/prevalence-by-mental-and-substance-use-disorder.csv')

In [83]:
aa = DataInfo(a)
aa.clean()

Index(['Country', 'Year',
       'Prevalence - Schizophrenia - Sex: Both - Age: Age-standardized (Percent)',
       'Prevalence - Bipolar disorder - Sex: Both - Age: Age-standardized (Percent)',
       'Prevalence - Eating disorders - Sex: Both - Age: Age-standardized (Percent)',
       'Prevalence - Anxiety disorders - Sex: Both - Age: Age-standardized (Percent)',
       'Prevalence - Drug use disorders - Sex: Both - Age: Age-standardized (Percent)',
       'Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent)',
       'Prevalence - Alcohol use disorders - Sex: Both - Age: Age-standardized (Percent)'],
      dtype='object')

In [84]:
a_dfincome = aa.dfincome()

In [85]:
a_dfincome

,Income,Year,Prevalence - Schizophrenia - Sex: Both - Age: Age-standardized (Percent),Prevalence - Bipolar disorder - Sex: Both - Age: Age-standardized (Percent),Prevalence - Eating disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Anxiety disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Drug use disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Alcohol use disorders - Sex: Both - Age: Age-standardized (Percent)
6630,World Bank High Income,1990,0.349837,0.786395,0.390832,5.080294,1.377799,3.728780,2.238104
6631,World Bank High Income,1991,0.351302,0.787030,0.397064,5.081799,1.394368,3.743666,2.219053
6632,World Bank High Income,1992,0.352642,0.787801,0.402772,5.084536,1.410451,3.761546,2.199737
6633,World Bank High Income,1993,0.353803,0.788598,0.407782,5.087854,1.425537,3.781520,2.181322
6634,World Bank High Income,1994,0.354764,0.789333,0.411640,5.091523,1.438795,3.802907,2.164989
...,...,...,...,...,...,...,...,...,...
6745,World Bank Upper Middle Income,2015,0.308526,0.475078,0.164308,4.093712,0.706593,3.329720,1.514542
6746,World Bank Upper Middle Income,2016,0.310809,0.477434,0.168254,4.138800,0.725803,3.331579,1.511265
6747,World Bank Upper Middle Income,2017,0.313086,0.479685,0.171563,4.185851,0.746686,3.332059,1.511673
6748,World Bank Upper Middle Income,2018,0.312974,0.481878,0.173578,4.192571,0.748686,3.330413,1.517199
6749,World Bank Upper Middle Income,2019,0.312283,0.484107,0.175025,4.181423,0.747494,3.322933,1.520577

<__main__.DataInfo object at 0x00000209A0247548>